# 数据源配置
spring:
    datasource:
        # 主库数据源
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          #url: jdbc:mysql://47.94.105.131:3306/eceas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
          url: jdbc:mysql://127.0.0.1:3306/sinosoft?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          # 初始连接数
          initial-size: 5
          # 最小连接池数量
          min-idle: 10
          # 最大连接池数量
          max-active: 20
          # 配置获取连接等待超时的时间
          max-wait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          # 配置一个连接在池中最大生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 900000
          # 配置检测连接是否有效
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          web-stat-filter:
              enabled: true
          stat-view-servlet:
              enabled: true
              # 设置白名单，不填则允许所有访问
              allow:
              url-pattern: /druid/*
              # 控制台管理用户名和密码
              login-username:
              login-password:
          filter:
              stat:
                  enabled: true
                  # 慢SQL记录
                  log-slow-sql: true
                  slow-sql-millis: 1000
                  merge-sql: true
              wall:
                  config:
                      multi-statement-allow: true
        # 从库数据源
        cluster:
        - key: gis
          driver-class-name: org.postgresql.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:postgresql://124.204.68.210:31179/gis
#          url: jdbc:postgresql://localhost:5432/postgis_25_sample
          username: postgres
          password: 123456
        - key: spider
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 爬虫数据源开关/默认关闭
          enabled: true
          url: jdbc:mysql://47.94.105.131:3306/weather?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 123456